export const SetNames = [
    'Aether Revolt',
    'Alara Reborn',
    'Alliances',
    'Amonkhet',
    'Amonkhet Invocations',
    'Amonkhet Remastered',
    'Anthologies',
    'Antiquities',
    'Apocalypse',
    'Arabian Nights',
    'Archenemy',
    'Archenemy: Nicol Bolas',
    'Avacyn Restored',
    'Battlebond',
    'Battle for Zendikar',
    'Betrayers of Kamigawa',
    'Born of the Gods',
    "Born of the Gods Hero's Path",
    "Champions of Kamigawa",
    'Chronicles',
    'Classic Sixth Edition',
    'Coldsnap',
    'Commander 2011',
    'Commander 2013',
    'Commander 2014',
    'Commander 2015',
    'Commander 2016',
    'Commander 2017',
    'Commander 2018',
    'Commander 2019',
    'Commander 2020',
    'Commander Anthology Volume II',
    'Commander Anthology',
    "Commander's Arsenal",
    'Commander Legends',
    'Conspiracy: Take the Crown',
    'Conspiracy',
    'Conflux',
    'Core Set 2019',
    'Core Set 2020',
    'Core Set 2021',
    'Dark Ascension',
    'Darksteel',
    'Deckmasters',
    'Dissension',
    'Dominaria',
    'Double Masters',
    'Dragons of Tarkir',
    "Dragon's Maze",
    'Eighth Edition',
    'Eldritch Moon',
    'Eternal Masters',
    'Eventide',
    'Exodus',
    'Explorers of Ixalan',
    'Fallen Empires',
    'Fate Reforged',
    'Fifth Dawn',
    'Fifth Edition',
    'Fourth Edition',
    'From the Vault: Angels',
    'From the Vault: Annihilation',
    'From the Vault: Dragons',
    'From the Vault: Exiled',
    'From the Vault: Legends',
    'From the Vault: Lore',
    'From the Vault: Realms',
    'From the Vault: Relics',
    'From the Vault: Transform',
    'From the Vault: Twenty',
    'Future Sight',
    'Gatecrash',
    'Guildpact',
    'Guilds of Ravnica',
    'Homelands',
    'Hour of Devastation',
    'Ice Age',
    'Iconic Masters',
    'Ikoria: Lair of Behemoths',
    'Invasion',
    'Innistrad',
    'Ixalan',
    'Journey into Nyx',
    "Journey into Nyx Hero's Path",
    'Judgment',
    'Jumpstart',
    'Kaladesh',
    'Kaladesh Inventions',
    'Khans of Tarkir',
    'Legends',
    'Legions',
    'Limited Edition Alpha',
    'Limited Edition Beta',
    'Lorwyn',
    'Magic 2010',
    'Magic 2011',
    'Magic 2012',
    'Magic 2013',
    'Magic 2014',
    'Magic 2015',
    'Magic Origins',
    'Masters Edition',
    'Masters Edition II',
    'Masters Edition III',
    'Masters Edition IV',
    'Mercadian Masques',
    'Mirage',
    'Mirrodin',
    'Mirrodin Besieged',
    'Modern Horizons',
    'Modern Masters 2015',
    'Modern Masters 2017',
    'Modern Masters',
    'Morningtide',
    'Mystery Booster',
    'Mystery Booster Playtest Cards',
    'Mythic Edition',
    'Nemesis',
    'New Phyrexia',
    'Ninth Edition',
    'Oath of the Gatewatch',
    'Odyssey',
    'Onslaught',
    'Planar Chaos',
    'Planechase',
    'Planeshift',
    'Portal',
    'Portal Second Age',
    'Portal Three Kingdoms',
    'Prophecy',
    'Ravnica Allegiance',
    'Ravnica: City of Guilds',
    'Return to Ravnica',
    'Revised Edition',
    'Rise of the Eldrazi',
    'Rivals of Ixalan',
    'Saviors of Kamigawa',
    'Scars of Mirrodin',
    'Scourge',
    'Secret Lair Drop',
    'Seventh Edition',
    'Shadowmoor',
    'Shadows over Innistrad',
    'Shards of Alara',
    'Signature Spellbook: Jace',
    'Signature Spellbook: Gideon',
    'Signature Spellbook: Chandra',
    'Stronghold',
    'Tarkir Dragonfury',
    'Tempest',
    'Tempest Remastered',
    'Tenth Edition',
    'The Dark',
    'Theros',
    'Theros Beyond Death',
    "Theros Hero's Path",
    'Throne of Eldraine',
    'Time Spiral',
    'Time Spiral Remastered',
    'Time Spiral Timeshifted',
    'Torment',
    "Ugin's Fate",
    'Ultimate Masters',
    'Unglued',
    'Unhinged',
    'Unlimited Edition',
    'Unsanctioned',
    'Unstable',
    "Urza's Destiny",
    "Urza's Legacy",
    "Urza's Saga",
    'Vintage Masters',
    'Visions',
    'War of the Spark',
    'Weatherlight',
    'Worldwake',
    'Zendikar',
    'Zendikar Expeditions',
    'Zendikar Rising',
    'Zendikar Rising Commander',
    'Zendikar Rising Expeditions',
]
