export const SetNames = [
    'Tenth Edition',
    'Unlimited Edition',
    'Double Masters',
    'Revised Edition',
    'Fourth Edition',
    'Fifth Dawn',
    'Fifth Edition',
    'Classic Sixth Edition',
    'Seventh Edition',
    'Eighth Edition',
    'Ninth Edition',
    'Aether Revolt',
    'Amonkhet',
    'Amonkhet Remastered',
    'Shards of Alara',
    'Alliances',
    'Apocalypse',
    'Alara Reborn',
    'Archenemy',
    'Arabian Nights',
    'Anthologies',
    'Antiquities',
    'Avacyn Restored',
    'Battlebond',
    'Battle for Zendikar',
    'Born of the Gods',
    'Betrayers of Kamigawa',
    'Commander 2013',
    'Commander 2014',
    'Commander 2015',
    'Commander 2016',
    'Commander 2017',
    'Commander 2018',
    'Commander 2019',
    'Commander 2020',
    "Champions of Kamigawa",
    'Chronicles',
    "Commander's Arsenal",
    'Commander Anthology Volume II',
    'Commander Anthology',
    'Mystery Booster Playtest Cards',
    'Commander 2011',
    'Commander Legends',
    'Conspiracy: Take the Crown',
    'Conspiracy',
    'Conflux',
    'Coldsnap',
    "Dragon's Maze",
    'Dissension',
    'Dark Ascension',
    'Deckmasters',
    'Dominaria',
    'From the Vault: Dragons',
    'The Dark',
    'Darksteel',
    'Dragons of Tarkir',
    'Archenemy: Nicol Bolas',
    'Explorers of Ixalan',
    'Throne of Eldraine',
    'Eternal Masters',
    'Eldritch Moon',
    'Eventide',
    'Exodus',
    'Zendikar Expeditions',
    'Fallen Empires',
    'Fate Reforged',
    'Future Sight',
    'Guildpact',
    'Guilds of Ravnica',
    'Gatecrash',
    'Homelands',
    'Planechase',
    'Hour of Devastation',
    'Ice Age',
    'Ikoria: Lair of Behemoths',
    'Iconic Masters',
    'Invasion',
    'Innistrad',
    'Jumpstart',
    'Journey into Nyx',
    'Judgment',
    'Kaladesh',
    'Khans of Tarkir',
    'Limited Edition Alpha',
    'Limited Edition Beta',
    'Legends',
    'Legions',
    'Lorwyn',
    'Magic 2010',
    'Magic 2011',
    'Magic 2012',
    'Magic 2013',
    'Magic 2014',
    'Magic 2015',
    'Core Set 2019',
    'Core Set 2020',
    'Core Set 2021',
    'Mystery Booster',
    'Mirrodin Besieged',
    'Masters Edition',
    'Masters Edition II',
    'Masters Edition III',
    'Masters Edition IV',
    'Mythic Edition',
    'Modern Horizons',
    'Mirage',
    'Modern Masters 2015',
    'Modern Masters 2017',
    'Modern Masters',
    'Mercadian Masques',
    'Morningtide',
    'Amonkhet Invocations',
    'Kaladesh Inventions',
    'Mirrodin',
    'Nemesis',
    'New Phyrexia',
    'Odyssey',
    'Oath of the Gatewatch',
    'Onslaught',
    'Magic Origins',
    'Portal Second Age',
    'Prophecy',
    'Planar Chaos',
    'Planeshift',
    'Portal',
    'Portal Three Kingdoms',
    'Tarkir Dragonfury',
    'Ravnica: City of Guilds',
    'Rivals of Ixalan',
    'Ravnica Allegiance',
    'Rise of the Eldrazi',
    'Return to Ravnica',
    'Scourge',
    'Shadowmoor',
    'Secret Lair Drop',
    'Shadows over Innistrad',
    'Saviors of Kamigawa',
    'Scars of Mirrodin',
    'Signature Spellbook: Jace',
    'Signature Spellbook: Gideon',
    'Signature Spellbook: Chandra',
    'Stronghold',
    'Theros Beyond Death',
    "Theros Hero's Path",
    "Born of the Gods Hero's Path",
    "Journey into Nyx Hero's Path",
    'Theros',
    'Tempest',
    'Torment',
    'Tempest Remastered',
    'Time Spiral Timeshifted',
    'Time Spiral',
    'Time Spiral Remastered',
    "Urza's Destiny",
    "Ugin's Fate",
    'Unglued',
    "Urza's Legacy",
    'Ultimate Masters',
    'Unsanctioned',
    'Unhinged',
    "Urza's Saga",
    'Unstable',
    'From the Vault: Exiled',
    'From the Vault: Relics',
    'From the Vault: Legends',
    'From the Vault: Realms',
    'From the Vault: Twenty',
    'From the Vault: Annihilation',
    'From the Vault: Angels',
    'From the Vault: Lore',
    'From the Vault: Transform',
    'Visions',
    'Vintage Masters',
    'War of the Spark',
    'Weatherlight',
    'Worldwake',
    'Ixalan',
    'Zendikar',
    'Zendikar Rising Commander',
    'Zendikar Rising Expeditions',
    'Zendikar Rising',
]
